# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180408_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
