# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 11:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_article_modified_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_auto_20180408_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'verbose_name': '回复评论',
                'verbose_name_plural': '回复评论',
            },
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.UserComment'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
