# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 15:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180416_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
