# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20180418_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='article',
        ),
        migrations.AddField(
            model_name='userlike',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='文章数据ID'),
        ),
    ]
