# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180408_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_numbers',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_numbers',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
