# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180408_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
