# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
    ]
