# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180414_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('reset', '重置密码')], default='register', max_length=10, verbose_name='发送类型'),
        ),
    ]
