# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverifycode_send_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifycode',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='emailverifycode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverifycode',
            name='email',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='emailverifycode',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
    ]
